### ISSUE TITLE
gRPC proto XML

### ISSUE THREAD

**Issue by mirceaulinic** [cisco-ie/ios-xr-grpc-python#2]
Hi @skkumaravel,

Thanks a lot for providing these examples!

I've got just a quick question: is it possible to specify in the [proto file](https://github.com/CiscoDevNet/grpc-getting-started/blob/master/IDL/ems_grpc.proto) to return XML instead of JSON?

Regards,
Mircea

**Comment by skkumaravel** [comment]
HI Mircea,

Unfortunately you cannot. The IOS-XR router doesn't support XML streaming through grpc. Even if you change the proto file on the local side, the server side doesn't change.

-Karthik
