### ISSUE TITLE
Deadline Exceeded

### ISSUE THREAD

**Issue by Maikor** [cisco-ie/ios-xr-grpc-python#4]
hello, i tried to execute example on 6.1.1 IOS-XRv. output below: 

vagrant@vagrant-ubuntu-trusty-64:~/cisco_grpc_python$ python grpc_example.py
Traceback (most recent call last):
  File "grpc_example.py", line 15, in <module>
    main()
  File "grpc_example.py", line 10, in main
    result = client.getconfig(path)
  File "/home/vagrant/cisco_grpc_python/client/cisco_grpc_client.py", line 58, in getconfig
    for response in responses:
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 153, in next
    return self._next()
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 147, in _next
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.ExpirationError: ExpirationError(code=StatusCode.DEADLINE_EXCEEDED, details="Deadline Exceeded")

**Comment by skkumaravel** [comment]
Hi can you provide some more info. Can you copy paste your show run and show version in IOS-XRv CLI.

**Comment by Maikor** [comment]
Sure thing. Little bit old version?
Cisco IOS XR Software, Version 6.1.1.19I
Copyright (c) 2013-2016 by Cisco Systems, Inc.

Build Information:
 Built By     : rwellum
 Built On     : Tue Jun 21 08:21:46 EDT 2016
 Build Host   : rtp-ads-474
 Workspace    : /nobackup/rwellum/xr-dev
 Version      : 6.1.1.19I
 Location     : /opt/cisco/XR/packages/

cisco IOS XRv x64 () processor
System uptime is 2 hours, 38 minutes

**Comment by skkumaravel** [comment]
Hi Sorry for the late reply. 
Could you update to the latest version. I just tested and had some issues on older versions. I have tested on 23i and above.
